# Generated by Django 2.0.7 on 2019-06-05 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_card_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
